<?php
defined('ABSPATH') || exit;

global $wpsp_e_all_controls;
global $wpsp_slick_defaults;
global $wpsp_e_general_controls;
$wpsp_e_general_controls = array( 'slidesToScroll', 'dots', 'infinite', 'centerMode', 'autoplay', 'arrows', 'speed', 'breakpoint' );

$wpsp_e_all_controls = array(
    'switcher' => array(
        'accessibility'    => true,
        'adaptiveHeight'   => false,
        'autoplay'         => false,
        'arrows'           => true,
        'fade'             => false,
        'draggable'        => true,
        'focusOnSelect'    => false,
        'infinite'         => true,
        'mobileFirst'      => false,
        'pauseOnFocus'     => true,
        'pauseOnHover'     => true,
        'pauseOnDotsHover' => false,
        'swipe'            => true,
        'swipeToSlide'     => false,
        'touchMove'        => true,
        'useCSS'           => true,
        'useTransform'     => true,
        'variableWidth'    => false,
        'vertical'         => false,
        'verticalSwiping'  => false,
        'rtl'              => false,
        'waitForAnimate'   => true,
        'dots'             => false,
        'centerMode'       => false,
    ),
    'text'     => array(
        'asNavFor'      => '',
        'appendArrows'  => '',
        'appendDots'    => '',
        'prevArrow'     => '',
        'nextArrow'     => '',
        'customPaging'  => '',
        'respondTo'     => '',
        'slide'         => '',
        'centerPadding' => '50px',
        'easing'        => '',
        'cssEase'       => '',
        'lazyLoad'      => 'ondemand',
    ),
    'select'   => array(
        'easing'  => array( 'linear', 'easeOutElastic' ),
        'cssEase' => array( 'ease', 'ease-out', 'linear' ),
    ),
    'integer'  => array(
        'autoplaySpeed'  => 3000,
        'edgeFriction'   => 0.35,
        'initialSlide'   => 0,
        'touchThreshold' => 5,
        'rows'           => 1,
        'slidesPerRow'   => 1,
        'slidesToShow'   => 1,
        'slidesToScroll' => 1,
        'speed'          => 500,
        'zIndex'         => 1000,
    ),
);

$wpsp_slick_defaults = array(
    "accessibility"    => true,
    "adaptiveHeight"   => false,
    "appendArrows"     => "",
    "appendDots"       => "",
    "arrows"           => true,
    "asNavFor"         => "",
    "autoplay"         => false,
    "autoplaySpeed"    => 3000,
    "centerMode"       => false,
    "centerPadding"    => "50px",
    "cssEase"          => "ease",
    "customPaging"     => null,
    "dots"             => false,
    "dotsClass"        => "slick-dots",
    "draggable"        => true,
    "easing"           => "linear",
    "edgeFriction"     => 0.15,
    "fade"             => false,
    "focusOnSelect"    => false,
    "infinite"         => true,
    "initialSlide"     => 0,
    "lazyLoad"         => "ondemand",
    "mobileFirst"      => false,
    "nextArrow"        => "",
    "pauseOnDotsHover" => false,
    "pauseOnFocus"     => true,
    "pauseOnHover"     => true,
    "prevArrow"        => "",
    "respondTo"        => "",
    "rows"             => 1,
    "rtl"              => false,
    "settings"         => array(),
    "slide"            => "",
    "slidesPerRow"     => 1,
    "slidesToScroll"   => 1,
    "slidesToShow"     => 1,
    "speed"            => 300,
    "swipe"            => true,
    "swipeToSlide"     => false,
    "touchMove"        => true,
    "touchThreshold"   => 5,
    "useCSS"           => true,
    "useTransform"     => true,
    "variableWidth"    => false,
    "vertical"         => false,
    "verticalSwiping"  => false,
    "waitForAnimate"   => true,
    "zIndex"           => 1000,
    "responsive"       => array(),
    "breakpoint"       => 0,
    "focusOnChange"    => true,
    
); 